name: media ink
favicon: null
layout_spectrum: 0.24374
typography_spectrum: 0.3643654310144484
title: Mediaink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0704'
    - '#d1c0b6'
    - '#fffdff'
    - '#ab978e'
    - '#736c69'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
