name: media ink
favicon: null
layout_spectrum: 0.27733952226117253
typography_spectrum: 0.3643654310144484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5704740285873413
  lightness: 0.5857780955266207
  saturation: 0.5837877076119184
  rhythmicContrast: 0.8229292104952037
purpose: []
